name: Manhunt
version: '${project.version}'
main: top.mpt.huihui.manhunt.Manhunt
api-version: '1.13'

commands:
  manhunt:
    description: Manhunt

permissions:
    manhunt.any:
      description: Allows manhunt command
      default: true
    manhunt.op:
      description: Allows manhunt op command
      default: op
